import { MD3LightTheme, type MD3Theme } from "react-native-paper";

export const ecoTheme: MD3Theme = {
  ...MD3LightTheme,
  roundness: 14,
  colors: {
    ...MD3LightTheme.colors,
    primary: "#1B5E20",
    onPrimary: "#FFFFFF",
    primaryContainer: "#DDF7DF",
    onPrimaryContainer: "#0A2E12",
    secondary: "#2E7D32",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#E9F6EA",
    onSecondaryContainer: "#16351A",
    tertiary: "#0F766E",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#D7F2EF",
    onTertiaryContainer: "#073A36",
    error: "#B42318",
    onError: "#FFFFFF",
    errorContainer: "#FEE4E2",
    onErrorContainer: "#7A271A",
    background: "#F4F8F3",
    onBackground: "#112019",
    surface: "#FFFFFF",
    onSurface: "#112019",
    surfaceVariant: "#E3ECE1",
    onSurfaceVariant: "#2C3B31",
    outline: "#6F7F74",
    outlineVariant: "#B7C5BA",
    inverseSurface: "#233127",
    inverseOnSurface: "#ECF4EC",
    inversePrimary: "#8ACF94",
    elevation: {
      ...MD3LightTheme.colors.elevation,
      level0: "transparent",
      level1: "#EEF5EE",
      level2: "#E7F1E8",
      level3: "#E1ECE2",
      level4: "#DAE8DC",
      level5: "#D4E4D6",
    },
    surfaceDisabled: "rgba(17, 32, 25, 0.12)",
    onSurfaceDisabled: "rgba(17, 32, 25, 0.38)",
    backdrop: "rgba(22, 45, 28, 0.35)",
  },
};
